name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
     container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'centos-latest' ]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: build.sh
